### ISSUE TITLE
Plugin doesn't recognize functions

### ISSUE THREAD

**Issue by leanazulyoro** [oliver006/drone-gcf#10]
Hello all, I'm trying to use this plugin, but I do not seam to get it correctly configured.
This is my .drone.yml:

```yaml
---
kind: pipeline
name: deploy-staging

steps:
  - name: restore_cache
    image: plugins/s3-cache
    settings:
      pull: true
      root: drone_cache
      endpoint: https://storage.googleapis.com
      access_key:
        from_secret: gcs_access_key
      secret_key:
        from_secret: gcs_secret_key
      restore: true

  - name: npm_install
    image: node:12-alpine
    commands:
      - npm install
    depends_on:
      - restore_cache

  - name: rebuild_cache
    image: plugins/s3-cache
    settings:
      pull: true
      root: drone_cache
      endpoint: https://storage.googleapis.com
      access_key:
        from_secret: gcs_access_key
      secret_key:
        from_secret: gcs_secret_key
      rebuild: true
      mount:
        - node_modules
    depends_on:
      - npm_install

  - name: npm_run_build
    image: node:12-alpine
    commands:
      - npm run build
    depends_on:
      - npm_install

  - name: deploy_cf
    depends_on:
      - npm_run_build
    image: oliver006/drone-gcf
    settings:
      action: deploy
      project: my-project-staging
      token:
        from_secret: token
      runtime: nodejs10
      env_secret_sql_user:
        from_secret: sql_user_stg
      env_secret_sql_password:
        from_secret: sql_password_stg
      env_secret_instance_connection_name:
        from_secret: instance_connection_name_stg
      env_secret_firestore_project_id:
        from_secret: firestore_project_id_stg
      env_secret_firestore_collection_name:
        from_secret: firestore_collection_name_stg
      functions:
        - MyFunctionName:
          - trigger: http
            memory: 2048MB
            runtime: nodejs10
            region: us-east1
            allow_unauthenticated: true
            environment:
              - LOGGING: true
                NODE_ENV: production
trigger:
  branch:
    - develop
  event:
    - push

```

When I run this pipeline, the "deploy_cf" fails with this:
```
2020/07/14 19:34:27 Drone-GCF Plugin  version: [not-tagged]   hash:    date: 2020-07-10-16:51:55
2020/07/14 19:34:27 Missing or invalid runtime [] for function: [{"MyFunctionName":[{"allow_unauthenticated":true
2020/07/14 19:34:27 Missing or invalid runtime [] for function: "environment":[{"LOGGING":true
2020/07/14 19:34:27 Missing or invalid runtime [] for function: "NODE_ENV":"production"}]
2020/07/14 19:34:27 Missing or invalid runtime [] for function: "memory":"2048MB"
2020/07/14 19:34:27 Missing or invalid runtime [] for function: "region":"us-east1"
2020/07/14 19:34:27 Missing or invalid runtime [] for function: "runtime":"nodejs10"
2020/07/14 19:34:27 Missing or invalid runtime [] for function: "trigger":"http"}]}]
2020/07/14 19:34:27 parseConfig() err: Didn't find any functions
```

It seams to mess up when parsing the yaml? It's not recognizing the "runtime" field, and doesn't even seam to recognize that there are any functions.
I'm sorry if this is a dumb syntax error from my part, but I don't see it.

**Comment by oliver006** [comment]
Hmm, that's interesting. From the error message it looks like the plugin is not parsing the config correctly, it interprets the whole function json blob as the name of the function.

What version of drone are you using?

**Comment by leanazulyoro** [comment]
hi @oliver006, I'm using drone 1.6.5

**Comment by leanazulyoro** [comment]
I have cero experience in go to  attempt at understanding if there is something wrong in the code when parsing the yaml, but a simple yaml to json tool would output this json for the "deploy_cf" step:
```json
{
        "name": "deploy_cf",
        "depends_on": [
           "npm_run_build"
        ],
        "image": "oliver006/drone-gcf",
        "settings": {
           "action": "deploy",
           "project": "my-project-staging",
           "token": {
              "from_secret": "token"
           },
           "runtime": "nodejs10",
           "env_secret_sql_user": {
              "from_secret": "sql_user_stg"
           },
           "env_secret_sql_password": {
              "from_secret": "sql_password_stg"
           },
           "env_secret_instance_connection_name": {
              "from_secret": "instance_connection_name_stg"
           },
           "env_secret_firestore_project_id": {
              "from_secret": "firestore_project_id_stg"
           },
           "env_secret_firestore_collection_name": {
              "from_secret": "firestore_collection_name_stg"
           },
           "functions": [
              {
                 "MyFunctionName": [
                    {
                       "trigger": "http",
                       "memory": "2048MB",
                       "runtime": "nodejs10",
                       "region": "us-east1",
                       "allow_unauthenticated": true,
                       "environment": [
                          {
                             "LOGGING": true,
                             "NODE_ENV": "production"
                          }
                       ]
                    }
                 ]
              }
           ]
        }
     }
```

**Comment by leanazulyoro** [comment]
@oliver006 I narrowed it down to boolean values, both the `allow_unauthenticated: true` and the environment variable `LOGGING: true` caused the issue. Passing them as strings solved it:
```yaml
---
kind: pipeline
name: deploy-staging

steps:
  - name: restore_cache
    image: plugins/s3-cache
    settings:
      pull: true
      root: drone_cache
      endpoint: https://storage.googleapis.com
      access_key:
        from_secret: gcs_access_key
      secret_key:
        from_secret: gcs_secret_key
      restore: true

  - name: npm_install
    image: node:12-alpine
    commands:
      - npm install
    depends_on:
      - restore_cache

  - name: rebuild_cache
    image: plugins/s3-cache
    settings:
      pull: true
      root: drone_cache
      endpoint: https://storage.googleapis.com
      access_key:
        from_secret: gcs_access_key
      secret_key:
        from_secret: gcs_secret_key
      rebuild: true
      mount:
        - node_modules
    depends_on:
      - npm_install

  - name: npm_run_build
    image: node:12-alpine
    commands:
      - npm run build
    depends_on:
      - npm_install

  - name: deploy_cf
    depends_on:
      - npm_run_build
    image: oliver006/drone-gcf
    settings:
      action: deploy
      project: my-project-staging
      token:
        from_secret: token
      runtime: nodejs10
      env_secret_sql_user:
        from_secret: sql_user_stg
      env_secret_sql_password:
        from_secret: sql_password_stg
      env_secret_instance_connection_name:
        from_secret: instance_connection_name_stg
      env_secret_firestore_project_id:
        from_secret: firestore_project_id_stg
      env_secret_firestore_collection_name:
        from_secret: firestore_collection_name_stg
      functions:
        - MyFunctionName:
          - trigger: http
            memory: 2048MB
            runtime: nodejs10
            region: us-east1
            allow_unauthenticated: "true"
            environment:
              - LOGGING: "true"
                NODE_ENV: production
trigger:
  branch:
    - develop
  event:
    - push
```

I don't know if this is the expected behaviour, but you may consider changing the docs to use `allow_unauthenticate: "true"` if anyone else is experiencing this problem.

thanks for the plugin and attention!
