### ISSUE TITLE
Add option to set delimeter for environment variables

### ISSUE THREAD

**Issue by leanazulyoro** [oliver006/drone-gcf#14]
Hi, me again, I have this case in which I'm attempting to set an env variable in the CF which contains comma (",") characters.
This is what comes up in the log:

```
2020/07/15 20:11:49 Drone-GCF Plugin  version: [not-tagged]   hash:    date: 2020-07-10-16:51:55
2020/07/15 20:11:49 Using project ID: xxxxxxxxxxx
Google Cloud SDK 290.0.1
alpha 2020.04.24
beta 2020.04.24
bq 2.0.56
core 2020.04.24
gsutil 4.49
kubectl 2020.04.24
Activated service account credentials for: [xxxx@xxxxx.iam.gserviceaccount.com]
ERROR: (gcloud.functions.deploy) argument --set-env-vars: Bad syntax for dict arg: [XNuWskz]. Please see `gcloud topic flags-file` or `gcloud topic escaping` for information on providing list or dictionary flag values with special characters.
Usage: gcloud functions deploy (NAME : --region=REGION) [optional flags]
  optional flags may be  --allow-unauthenticated | --clear-env-vars |
                         --clear-labels | --clear-max-instances |
                         --clear-vpc-connector | --egress-settings |
                         --entry-point | --env-vars-file | --help |
                         --ignore-file | --ingress-settings | --max-instances |
                         --memory | --region | --remove-env-vars |
                         --remove-labels | --retry | --runtime |
                         --service-account | --set-env-vars | --source |
                         --stage-bucket | --timeout | --trigger-bucket |
                         --trigger-event | --trigger-http | --trigger-resource |
                         --trigger-topic | --update-env-vars | --update-labels |
                         --vpc-connector

For detailed information on this command and its flags, run:
  gcloud functions deploy --help
2020/07/15 20:11:50 runConfig() err: error: exit status 2
```

if you go and check those  `gcloud topic flags-file` or `gcloud topic escaping`, you'll find two posibilities to allow the use of commas and other special characters in the values for a "dictionary flag", which happens to be the case for `---set-env-vars`.
To sum up, what needs to happen is that when the command is building it's flags, it should allow to build it like this:
`--set-env-vars=^DELIM^`, maybe pass that DELIM in a `environment_delimiter` setting?

That would allow us to have commas (and any other character) in the values for our environment variables. like so:
```yaml
- name: deploy-cloud-functions
    image: oliver006/drone-gcf
    settings:
      action: deploy
      project: xxxxxx
      token:
        from_secret: token
      functions:
        - MyFunction:
          - trigger: http
            runtime: nodejs10
            memory: 2048MB
            environment_delimiter: ";"
            environment:
              - SOME_ENV: "some,value,with,commas"
                SOME_OTHER_ENV: "someValueWithoutCommas"
```
which should result in this flag:
`--set-env-vars=^;^SOME_ENV=some,value,with,commas;SOME_OTHER_ENV=someValueWithoutCommas`
