### ISSUE TITLE
Receiving Error: 'Missing action' when action is set to deploy

### ISSUE THREAD

**Issue by emilysimonton** [oliver006/drone-gcf#21]
Hi @oliver006 ,
I am trying to use this plugin to deploy cloud functions in drone, however I keep receiving the following error in drone:
`parseConfig() err: Missing action` even though action is set. Please see my .drone.yml file below:

```
  deploy_cf_stg:
    image: oliver006/drone-gcf
    settings:
      action: deploy
      project: nyt-dssor-stg
      token:
        from_secret: gcf_credentials_stg
      runtime: python37
      functions:
        - status_check:
            - trigger: http
              source: cloud_functions
              entry_point: run_status_check
              function_name: status_check
              runtime: python37
              verbosity: info
```

Thanks in advance for your help!
