### ISSUE TITLE
[bug] deploying with multiple environment variables doesn't work

### ISSUE THREAD

**Issue by RayBB** [oliver006/drone-gcf#7]
```
 - name: deploy-cloud-func
    image: oliver006/drone-gcf:v1.6.0
    settings:
      action: deploy
      project: my-cloud-function-testing
      token:
        from_secret: google_credentials_dev
      runtime: nodejs10
      functions:
        - slack:
            - trigger: http
              environment:
                - firstkey: firstvalue
                - secondkey: secondvalue
```

When I use the above, only the first environment variable is deployed.
I believe it's because of [these lines](https://github.com/oliver006/drone-gcf/blob/master/main.go#L296-L297).

According to [the docs](https://cloud.google.com/sdk/gcloud/reference/functions/deploy#--set-env-vars), the flag should be used as `--set-env-vars=[KEY=VALUE,…]` but it seems we are using `:|:` as a separator.

It seems like it might be as simple as switching out the separator but maybe there's a reason that separator was being used in the first place?
